### ISSUE TITLE
Unable to Access FAERS Data Download Links (HTTP Error 404)

### ISSUE THREAD

**Issue by ZhenWang325429** [Yunuuuu/faers#5]
Hello,

I've encountered some issues while using the faers package and would appreciate any assistance.

Error with faers_meta() function
When running the faers_meta() function, I receive the following error message:

**Reading html: <https://fis.fda.gov/extensions/FPD-QDE-FAERS/FPD-QDE-FAERS.html>
open.connection(x, "rb"): HTTP error 404**
It seems to be caused by an inability to access the specified HTML page.

Error while downloading multiple data files
When attempting to download multiple data files using the faers package, running the following code:

**data4 <- faers(years = "2003", 
               quarters = c("q4"),
               dir = system.file("extdata", package = "faers"),
               compress_dir = tempdir())**

I encounter this error:

**Error in `download_inform()`:
! Cannot download 1 file
ℹ url: <https://fis.fda.gov/content/Exports/aers_ascii_2004q3.zip>
! status code: 404
✖ error message: NA**
This also seems to be due to an inability to access the specified URL.

Environment Information:
R version: 4.4.1
faers package version: 1.0.0

Attempted Solutions:
Verified that I can access other FDA-related pages and that my internet connection is stable.
Updated R and the faers package to the latest versions, but the issue persists.

Summary of Issues:
The HTML page for the faers_meta() function is inaccessible (HTTP 404 error).
The data download URL is inaccessible, returning an HTTP 404 error.

Assistance Needed:
Is there an alternative URL or method to obtain this data?
Have other users encountered similar issues, and are there any temporary workarounds?
Thank you!

**Comment by Yunuuuu** [comment]
The FAERS files are updated every three months, during which the service is unavailable. The FAERS system usually takes several days to resume operation. I have experienced this error in `Octorber`.

**Comment by ZhenWang325429** [comment]
Thank you for your reply and great work.

Regards,

**Comment by Yunuuuu** [comment]
You can check this [site](https://www.fda.gov/drugs/questions-and-answers-fdas-adverse-event-reporting-system-faers/fda-adverse-event-reporting-system-faers-latest-quarterly-data-files).
![image](https://github.com/Yunuuuu/faers/assets/19575010/acdf1ff6-120c-4a88-98b8-0c1a8901e371)

`faers_meta` did attached a metadata copy file, you can check with `faers_meta(internal = TRUE)`. For quarterly data files, since they're too big to be attached in a R package and `FAERS` don't gave other ways to download these files, you should just wait for the FAERS service.

**Comment by Yunuuuu** [comment]
Since this is not a problem of this package, I'll close this issue. Feel free to reopen it.
